name: CI workflow

# Trigger the workflow on push to main branch and on pull requests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    container:
      image: python:3.9-slim

    steps:
    # Step 1: Checkout the repository
    - name: Checkout
      uses: actions/checkout@v3

    # Step 2: Install Python dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 3: Lint the code using Flake8
    - name: Lint with flake8
      run: |
        flake8 service --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 service --count --max-complexity=10 --max-line-length=127 --statistics

    # Step 4: Run unit tests using Nose
    - name: Run unit tests with nose
      run: |
        nosetests -v --with-spec --spec-color --with-coverage --cover-package=app
